### ISSUE TITLE
Google drive link in README

### ISSUE THREAD

**Issue by ugurdogrusoz** [nursolukedi/2F.Farmio#2]
Is this a link to the document for meeting logs? If so, please rename it as:
Meeting logs: \<link\>

**Comment by nursolukedi** [comment]
Done.

**Comment by ugurdogrusoz** [comment]
@nursolukedi The link is to a folder, not a Google doc, where meeting logs are.
Also, when you resolve an issue, you should assign it back to the creator for them to verify and close.

**Comment by nursolukedi** [comment]
Sorry for closing them by myself and this issue is done.

**Comment by ugurdogrusoz** [comment]
@nursolukedi thanks! If it's done, assign it back to me please :)
