### ISSUE TITLE
doc directory

### ISSUE THREAD

**Issue by ugurdogrusoz** [nursolukedi/2F.Farmio#3]
Why create one if you're not going to use it?

**Comment by nursolukedi** [comment]
Eray opened it to try. Deleted.

**Comment by ugurdogrusoz** [comment]
@nursolukedi But you've been specifically asked (see Proj Desc Doc) you to create such a directory and put all documents there!

**Comment by eraysahin** [comment]
The folder was there actually. I don't know by whom it got deleted and why (probably by an unintended mistake). The analysis report is now moved to the "doc" folder.

**Comment by ugurdogrusoz** [comment]
You guys should read the instructions carefully. Such changes make it difficult for us that you respect the deadlines.
Please make sure the unstable branch has the same structure. Remember you are to merge the unstable branch to the master around deadlines (e.g. this Saturday).

**Comment by eraysahin** [comment]
Really sorry about that. Demir has fixed the folders' structure yesterday before the deadline.

**Comment by ugurdogrusoz** [comment]
Thanks
